"use client";

import { FormEvent, useState } from "react";
import { useDemoStore } from "./demo-store";

export function DepartmentsPage(){const{state}=useDemoStore();return <><div className="page-head"><div><h1>Departamentos</h1><p>La estructura de cada organización es configurable.</p></div></div><div className="grid grid-2">{state.departments.map(d=>{const open=state.tickets.filter(t=>t.departmentId===d.id&&t.status==="open").length;return <div className="card" key={d.id}><h2 className="section-title">{d.name}</h2><p className="meta">{open} tickets abiertos</p></div>;})}</div></>}
export function DecisionsPage(){const{state}=useDemoStore();const rows=state.tickets.filter(t=>t.status==="open"&&t.decisionNeeded);return <Module title="Decisiones" subtitle="Lo que necesita una definición explícita.">{rows.map(t=><div className="ticket" key={t.id}><div><h3>#{t.number} · {t.title}</h3><div className="meta"><span>{t.decisionNeeded}</span></div></div></div>)}</Module>}
export function InboxPage(){const{state,sendInbox}=useDemoStore();const[to,setTo]=useState(state.departments[0]?.name||"General");const[message,setMessage]=useState("");const submit=(e:FormEvent)=>{e.preventDefault();if(!message.trim())return;sendInbox(to,message.trim());setMessage("");};return <Module title="Inbox interno" subtitle="Pedidos, bloqueos y actualizaciones entre áreas sin salir del OS."><form className="row" onSubmit={submit} style={{marginBottom:16}}><select className="select" style={{maxWidth:220}} value={to} onChange={e=>setTo(e.target.value)}><option>General</option>{state.departments.map(d=><option key={d.id}>{d.name}</option>)}</select><input className="input" value={message} onChange={e=>setMessage(e.target.value)} placeholder="Escribí un mensaje interno"/><button className="btn">Enviar</button></form>{state.inbox.map(m=><div className="ticket" key={m.id}><div><h3>{m.from} → {m.to}</h3><div className="meta"><span>{m.message}</span><span>{new Date(m.createdAt).toLocaleString()}</span></div></div></div>)}</Module>}
export function HistoryPage(){const{state}=useDemoStore();return <Module title="Historial" subtitle="Audit log operativo append-only en el backend; demo local en esta vista."><table className="table"><thead><tr><th>Cuándo</th><th>Entidad</th><th>Acción</th><th>Detalle</th></tr></thead><tbody>{state.audit.map(a=><tr key={a.id}><td>{new Date(a.createdAt).toLocaleString()}</td><td>{a.entityType} · {a.entityId.slice(0,8)}</td><td>{a.action}</td><td>{a.detail}</td></tr>)}</tbody></table></Module>}
export function ArchivePage(){const{state}=useDemoStore();const rows=state.tickets.filter(t=>t.status==="done");return <Module title="Archivo" subtitle="Cerrar no borra. El trabajo terminado sigue siendo consultable.">{rows.map(t=><div className="ticket" key={t.id}><div><h3>#{t.number} · {t.title}</h3><div className="meta"><span>{t.evidence||"Sin evidencia"}</span></div></div></div>)}</Module>}
export function TeamPage(){const{state}=useDemoStore();return <Module title="Equipo" subtitle="Los responsables de tickets salen de memberships activas."><table className="table"><thead><tr><th>Perfil</th><th>Rol</th><th>Estado</th></tr></thead><tbody>{state.profiles.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.role}</td><td>{p.active?"Activo":"Inactivo"}</td></tr>)}</tbody></table></Module>}
export function SettingsPage(){const{state,resetDemo}=useDemoStore();return <Module title="Configuración" subtitle="Branding, terminología, módulos y reglas viven por organización."><div className="grid grid-2"><div className="card"><h2 className="section-title">Tenant</h2><p>{state.organization.name}</p><p className="meta">{state.organization.productName} · undo {state.organization.undoSeconds}s</p></div><div className="card"><h2 className="section-title">Demo</h2><p className="meta">Datos sintéticos guardados localmente en este navegador.</p><button className="btn secondary" onClick={resetDemo}>Reset demo</button></div></div><div className="notice" style={{marginTop:16}}>Con Supabase configurado, estas opciones se persisten por organization_id y quedan protegidas por RLS.</div></Module>}
function Module({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <><div className="page-head"><div><h1>{title}</h1><p>{subtitle}</p></div></div><div className="card">{children}</div></>}
